/**
 * @file constants.ts
 * @description Global constants for the Voicebot Console backend.
 * @module constants
 *
 */

export const API = {
  PREFIX: 'api',
  HEALTH: 'health',
  LLM: 'llm',
  RESPOND: 'respond',
  AGENT: 'agent',
  PROPERTIES: 'properties',
  VOICE: 'voice',
  SESSION: 'session',
  REQUEST_INPUT_KEY: 'input',
  RESPONSE_TEXT_KEY: 'text',
  RESPONSE_STATUS_KEY: 'status',
};

export const ENV_KEYS = {
  PORT: 'PORT',
  CORS_ORIGIN: 'CORS_ORIGIN',
  USE_LOCAL_LLM: 'USE_LOCAL_LLM',
  USE_TOOLS: 'USE_TOOLS',
  USE_RAG: 'USE_RAG',
  USE_REALTIME: 'USE_REALTIME',
  AGENT_DEBUG_LOGS: 'AGENT_DEBUG_LOGS',
  OLLAMA_BASE_URL: 'OLLAMA_BASE_URL',
  OLLAMA_MODEL: 'OLLAMA_MODEL',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  OPENAI_MODEL: 'OPENAI_MODEL',
  OPENAI_BASE_URL: 'OPENAI_BASE_URL',
  OPENAI_REALTIME_URL: 'OPENAI_REALTIME_URL',
  OPENAI_REALTIME_MODEL: 'OPENAI_REALTIME_MODEL',
  OPENAI_REALTIME_VOICE: 'OPENAI_REALTIME_VOICE',
  OPENAI_REALTIME_TRANSCRIBE_MODEL: 'OPENAI_REALTIME_TRANSCRIBE_MODEL',
  WEBRTC_ICE_SERVERS: 'WEBRTC_ICE_SERVERS',
  PROPERTIES_DATA_PATH: 'PROPERTIES_DATA_PATH',
  BRAVE_API_KEY: 'BRAVE_API_KEY',
  BRAVE_BASE_URL: 'BRAVE_BASE_URL',
  BRAVE_RESULT_COUNT: 'BRAVE_RESULT_COUNT',
};

export const ERRORS = {
  MISSING_ENV: 'Missing required environment variables:',
  INVALID_PORT: 'Invalid port value.',
  INVALID_NUMBER: 'Invalid numeric value.',
  LLM_FAILED: 'LLM request failed.',
  LLM_EMPTY: 'No response text was returned.',
  TOOL_INPUT_INVALID: 'Tool input is invalid.',
  TOOL_UNSUPPORTED: 'Tool is not supported.',
  SEARCH_FAILED: 'Search request failed.',
  TOOLS_DISABLED: 'Tooling is disabled.',
  RAG_DISABLED: 'RAG is disabled.',
  RAG_DATA_LOAD_FAILED: 'RAG data load failed.',
  RAG_QUERY_EMPTY: 'RAG query is empty.',
  AGENT_FAILED: 'Agent request failed.',
  AGENT_COERCED_NO_ANSWER: 'No usable answer was returned by the agent.',
  REALTIME_DISABLED: 'Realtime voice is disabled.',
  REALTIME_CONNECTION_FAILED: 'Realtime connection failed.',
  REALTIME_SESSION_FAILED: 'Realtime session failed.',
  REALTIME_CLIENT_INVALID: 'Realtime client event is invalid.',
  REALTIME_TOOL_FAILED: 'Realtime tool call failed.',
  WEBRTC_UNSUPPORTED: 'WebRTC is not supported.',
  WEBRTC_SESSION_INVALID: 'WebRTC session is invalid.',
};

export const DELIMITERS = {
  COMMA_SPACE: ', ',
  SPACE: ' ',
};

export const HTTP = {
  METHOD_POST: 'POST',
  METHOD_GET: 'GET',
  HEADER_AUTH: 'Authorization',
  HEADER_CONTENT_TYPE: 'Content-Type',
  CONTENT_TYPE_JSON: 'application/json',
  BEARER_PREFIX: 'Bearer ',
  HEADER_ACCEPT: 'Accept',
  HEADER_ACCEPT_ENCODING: 'Accept-Encoding',
  ACCEPT_JSON: 'application/json',
  ACCEPT_ENCODING: 'gzip',
};

export const BOOL = {
  TRUE: 'true',
};

export const OPENAI = {
  RESPONSES_PATH: '/responses',
  MODEL_KEY: 'model',
  INPUT_KEY: 'input',
  STORE_KEY: 'store',
  STORE_DISABLED: false,
  STORE_ENABLED: true,
  OUTPUT_KEY: 'output',
  OUTPUT_TEXT_PROPERTY: 'output_text',
  OUTPUT_MESSAGE_TYPE: 'message',
  OUTPUT_TEXT_TYPE: 'output_text',
  TOOLS_KEY: 'tools',
  TOOL_CHOICE_KEY: 'tool_choice',
  INSTRUCTIONS_KEY: 'instructions',
  PREVIOUS_RESPONSE_ID_KEY: 'previous_response_id',
  TOOL_TYPE_FUNCTION: 'function',
  OUTPUT_FUNCTION_CALL_TYPE: 'function_call',
  TOOL_CALL_OUTPUT_TYPE: 'function_call_output',
  TOOL_CALL_ID_KEY: 'call_id',
  TOOL_CALL_NAME_KEY: 'name',
  TOOL_CALL_ARGUMENTS_KEY: 'arguments',
  TOOL_OUTPUT_KEY: 'output',
  FUNCTION_NAME_KEY: 'name',
  FUNCTION_DESCRIPTION_KEY: 'description',
  FUNCTION_PARAMETERS_KEY: 'parameters',
  RESPONSE_ID_KEY: 'id',
};

export const REALTIME = {
  WS_PATH: '/ws/realtime',
  PROPERTIES_WS_PATH: '/ws/realtime/properties',
  QUERY_MODEL_KEY: 'model',
  SESSION_TYPE: 'realtime',
  AUDIO_FORMAT_PCM: 'audio/pcm',
  AUDIO_SAMPLE_RATE: 24000,
  TOOL_CHOICE_AUTO: 'auto',
  ERROR_TOKEN: 'error',
  INPUT_FORMAT_PCM16: 'pcm16',
  OUTPUT_FORMAT_PCM16: 'pcm16',
  OUTPUT_MODALITIES_AUDIO: ['audio'],
  TURN_DETECTION_DISABLED: null,
  TURN_DETECTION_SERVER_VAD: {
    type: 'server_vad',
    threshold: 0.5,
    prefix_padding_ms: 300,
    silence_duration_ms: 500,
    create_response: false,
    interrupt_response: true,
  },
};

export const WEBRTC = {
  WS_PATH: '/voice/webrtc',
  ICE_SERVERS_HEADER: 'x-forwarded-proto',
  SIGNALING_OFFER: 'webrtc.offer',
  SIGNALING_ANSWER: 'webrtc.answer',
  SIGNALING_ICE: 'webrtc.ice',
  SIGNALING_ERROR: 'webrtc.error',
  SIGNALING_READY: 'webrtc.ready',
  PLAYBACK_STARTED: 'session.playback.started',
  PLAYBACK_DONE: 'session.playback.done',
  ASSISTANT_SPEAKING: 'assistant.speaking',
  AUDIO_SAMPLE_RATE: 48000,
  AUDIO_BITS_PER_SAMPLE: 16,
  AUDIO_CHANNELS: 1,
};

export const REALTIME_KEYS = {
  TYPE: 'type',
  EVENT_ID: 'event_id',
  AUDIO: 'audio',
  AUDIO_INPUT: 'input',
  AUDIO_OUTPUT: 'output',
  AUDIO_FORMAT: 'format',
  AUDIO_FORMAT_TYPE: 'type',
  AUDIO_FORMAT_RATE: 'rate',
  AUDIO_TRANSCRIPTION: 'transcription',
  SESSION: 'session',
  RESPONSE: 'response',
  MODEL: 'model',
  INPUT_AUDIO_FORMAT: 'input_audio_format',
  OUTPUT_AUDIO_FORMAT: 'output_audio_format',
  OUTPUT_MODALITIES: 'output_modalities',
  VOICE: 'voice',
  TURN_DETECTION: 'turn_detection',
  INPUT_AUDIO_TRANSCRIPTION: 'input_audio_transcription',
  ITEM: 'item',
};

export const REALTIME_EVENTS = {
  SESSION_UPDATE: 'session.update',
  RESPONSE_CREATE: 'response.create',
  RESPONSE_CREATED: 'response.created',
  RESPONSE_CANCEL: 'response.cancel',
  RESPONSE_DONE: 'response.done',
  INPUT_AUDIO_CLEAR: 'input_audio_buffer.clear',
  INPUT_AUDIO_APPEND: 'input_audio_buffer.append',
  INPUT_AUDIO_COMMIT: 'input_audio_buffer.commit',
  INPUT_AUDIO_SPEECH_STARTED: 'input_audio_buffer.speech_started',
  OUTPUT_AUDIO_DELTA: 'response.output_audio.delta',
  OUTPUT_AUDIO_DONE: 'response.output_audio.done',
  OUTPUT_AUDIO_TRANSCRIPT_DELTA: 'response.output_audio_transcript.delta',
  OUTPUT_AUDIO_TRANSCRIPT_DONE: 'response.output_audio_transcript.done',
  INPUT_AUDIO_TRANSCRIPT_DELTA: 'conversation.item.input_audio_transcription.delta',
  INPUT_AUDIO_TRANSCRIPT_FAILED: 'conversation.item.input_audio_transcription.failed',
  CONVERSATION_ITEM_TRUNCATE: 'conversation.item.truncate',
  CONVERSATION_ITEM_CREATE: 'conversation.item.create',
  RESPONSE_FUNCTION_CALL_ARGUMENTS_DONE: 'response.function_call_arguments.done',
};

export const REALTIME_RELAY = {
  READY: 'realtime.ready',
  ERROR: 'realtime.error',
  CLOSED: 'realtime.closed',
  MESSAGE_KEY: 'message',
  CODE_KEY: 'code',
};

export const OLLAMA = {
  GENERATE_PATH: '/api/generate',
  MODEL_KEY: 'model',
  PROMPT_KEY: 'prompt',
  STREAM_KEY: 'stream',
  STREAM_VALUE: false,
  OPTIONS_KEY: 'options',
  OPTIONS_TEMPERATURE_KEY: 'temperature',
  OPTIONS_NUM_PREDICT_KEY: 'num_predict',
  RESPONSE_TEXT_KEY: 'response',
};

export const BRAVE = {
  SEARCH_PATH: '/res/v1/web/search',
  QUERY_PARAM: 'q',
  COUNT_PARAM: 'count',
  RESPONSE_WEB_KEY: 'web',
  RESPONSE_RESULTS_KEY: 'results',
  RESPONSE_TITLE_KEY: 'title',
  RESPONSE_URL_KEY: 'url',
  RESPONSE_DESCRIPTION_KEY: 'description',
  HEADER_SUBSCRIPTION: 'X-Subscription-Token',
};

export const TOOLS = {
  WEB_SEARCH: 'web_search',
  PROPERTY_SEARCH: 'search_properties',
};

export const TOOLING = {
  QUERY_KEY: 'query',
  COUNT_KEY: 'count',
  TOP_K_KEY: 'top_k',
  RESULTS_KEY: 'results',
  TOOL_INPUT_TYPE: 'object',
  TOOL_STRING_TYPE: 'string',
  TOOL_NUMBER_TYPE: 'number',
  SCHEMA_TYPE_KEY: 'type',
  SCHEMA_PROPERTIES_KEY: 'properties',
  SCHEMA_REQUIRED_KEY: 'required',
  SCHEMA_DESCRIPTION_KEY: 'description',
  SCHEMA_MINIMUM_KEY: 'minimum',
  SCHEMA_MAXIMUM_KEY: 'maximum',
  SCHEMA_DEFAULT_KEY: 'default',
  TOOL_INSTRUCTIONS:
    'Use the web_search tool when you need up-to-date or factual information from the web. Provide JSON input with a "query" string and optional "count" number. If the user does not need web data, respond normally.',
  PROPERTY_TOOL_INSTRUCTIONS:
    'You are a property listing assistant for a real estate agency. Use the search_properties tool for any request about listings, neighborhoods, prices, features, or availability. Answer only with information from the search_properties results. If the results are empty or insufficient, ask a concise follow-up question about location, budget, beds/baths, or property type. Do not invent listings or details.',
  WEB_SEARCH_DESCRIPTION:
    'Search the web for relevant, up-to-date information.',
  WEB_SEARCH_QUERY_DESCRIPTION: 'Search query for the web.',
  WEB_SEARCH_COUNT_DESCRIPTION: 'Number of results to return.',
  PROPERTY_SEARCH_DESCRIPTION:
    'Search local property listings stored in JSON files.',
  PROPERTY_SEARCH_QUERY_DESCRIPTION:
    'Search query describing desired property features, location, or budget.',
  PROPERTY_SEARCH_TOP_K_DESCRIPTION: 'Number of property results to return.',
};

export const DEFAULTS = {
  BRAVE_RESULT_COUNT: 5,
  PROPERTY_RESULT_COUNT: 5,
  WEBRTC_ICE_SERVERS: [{ urls: 'stun:stun.l.google.com:19302' }],
  WEBRTC_SESSION_TTL_MS: 5 * 60 * 1000,
};

export const LIMITS = {
  TOOL_MIN_COUNT: 3,
  TOOL_MAX_COUNT: 7,
  PROPERTY_MIN_COUNT: 1,
  PROPERTY_MAX_COUNT: 8,
  AGENT_MAX_STEPS: 4,
  AGENT_JSON_INDENT: 2,
  AGENT_TEMPERATURE: 0.2,
  AGENT_NUM_PREDICT: 220,
  AGENT_LOG_TRUNCATE: 600,
};

export const RAG = {
  PROPERTIES_DEFAULT_PATH: 'data/properties.json',
  FILE_ENCODING: 'utf8' as const,
  MIN_TOKEN_LENGTH: 2,
  STOP_WORDS: [
    'a',
    'an',
    'and',
    'are',
    'as',
    'at',
    'be',
    'by',
    'for',
    'from',
    'in',
    'is',
    'it',
    'near',
    'of',
    'on',
    'or',
    'the',
    'to',
    'with',
  ],
};

export const AGENT = {
  TYPE_KEY: 'type',
  NAME_KEY: 'name',
  ARGUMENTS_KEY: 'arguments',
  ANSWER_KEY: 'answer',
  MODE_TOOL: 'tool',
  MODE_FINAL: 'final',
  ROLE_SYSTEM: 'system',
  ROLE_USER: 'user',
  ROLE_ASSISTANT: 'assistant',
  ROLE_SYSTEM_LABEL: 'SYSTEM',
  ROLE_USER_LABEL: 'USER',
  ROLE_ASSISTANT_LABEL: 'ASSISTANT',
  ROLE_SEPARATOR: ':\n',
  BLOCK_SEPARATOR: '\n\n',
  SYSTEM_PROMPT:
    'You are a tool-using assistant.\n\nYou MUST respond with exactly one JSON object and nothing else (no markdown, no commentary).\n\nTo use web search:\n{"type":"tool","name":"web_search","arguments":{"query":"...","count":5}}\n\nTo answer the user:\n{"type":"final","answer":"..."}\n\nRules:\n- Use web_search when you need up-to-date info, facts, or verification.\n- When using web_search, choose a count between 3 and 7.\n- After receiving results, respond with a tool call or final answer.\n- Use only the provided search results; do not invent citations.',
  PROPERTY_SYSTEM_PROMPT:
    'You are a property listing assistant for a real estate agency.\n\nYou MUST respond with exactly one JSON object and nothing else (no markdown, no commentary).\n\nTo search listings:\n{"type":"tool","name":"search_properties","arguments":{"query":"...","top_k":5}}\n\nTo answer the user:\n{"type":"final","answer":"..."}\n\nRules:\n- Use search_properties for any request about listings, neighborhoods, prices, features, or availability.\n- Answer only with information from the search_properties results.\n- If results are empty or insufficient, ask a concise follow-up question about location, budget, beds/baths, or property type.\n- Do not invent listings or details.',
  INVALID_OUTPUT_PROMPT:
    'INVALID OUTPUT. You must output only valid JSON per schema. Try again now.',
  INVALID_SCHEMA_PROMPT:
    'INVALID JSON SHAPE. Output must match the schema exactly. Try again now.',
  LOCAL_TOOL_CALL_ID: 'local-web-search',
  TOOL_RESULT_PREFIX: 'Tool result:\n',
  TOOL_RESULT_SUFFIX: '\n\nNow continue and respond with JSON only.',
  FALLBACK_RESPONSE:
    'I could not complete the request within the step limit. Try a more specific question.',
  JSON_FENCE_START: '```json',
  JSON_FENCE_END: '```',
  RESULTS_HEADER: 'Web search results:',
  RESULT_INDEX_SUFFIX: '. ',
  RESULT_URL_LABEL: 'URL: ',
  RESULT_DESCRIPTION_LABEL: 'Summary: ',
  RESULT_LINE_BREAK: '\n',
  RESULT_BLOCK_BREAK: '\n\n',
};

export const LOGS = {
  BOOTSTRAP: 'Bootstrap',
  LOCAL_LLM_ENABLED: 'Local LLM enabled. model: ',
  OPENAI_ENABLED: 'OpenAI enabled. model: ',
  LOCAL_LLM_REQUEST: 'Local LLM request.',
  OPENAI_REQUEST: 'OpenAI request.',
  TOOL_REQUEST: 'Tool request.',
  TOOL_DISABLED: 'Tools disabled.',
  AGENT_REQUEST: 'Agent request.',
  OPENAI_ERROR_STATUS: 'OpenAI request failed. status: ',
  OPENAI_ERROR_BODY: 'OpenAI error body: ',
  AGENT_STEP: 'Agent step: ',
  AGENT_TOOL_CALL_COUNT: 'Agent tool calls: ',
  AGENT_TOOL_NAME: 'Agent tool name: ',
  AGENT_TOOL_QUERY: 'Agent tool query: ',
  AGENT_TOOL_RESULTS: 'Agent tool results: ',
  AGENT_ACTION_FINAL: 'Agent action: final',
  AGENT_ACTION_TOOL: 'Agent action: tool',
  AGENT_PARSE_FAILED: 'Agent parse failed.',
  AGENT_SCHEMA_FAILED: 'Agent schema failed.',
  AGENT_OUTPUT: 'Agent raw output: ',
  AGENT_FALLBACK: 'Agent fallback returned.',
  AGENT_NO_TOOL_CALLS: 'Agent tool calls: 0',
  AGENT_OPENAI_RESPONSE_ID: 'Agent response id: ',
  AGENT_OPENAI_NO_TOOL_CALLS: 'OpenAI no tool calls, returning response.',
  AGENT_TRUNCATED_SUFFIX: '...',
  AGENT_OPENAI_RESPONSE: 'OpenAI response: ',
  AGENT_OPENAI_TEXT: 'OpenAI response text: ',
  AGENT_OPENAI_TEXT_EMPTY: 'OpenAI response text empty.',
  AGENT_STEP_LIMIT: 'Agent step limit reached.',
  BRAVE_RESPONSE: 'Brave response: ',
  BRAVE_RESULTS: 'Brave results: ',
  BRAVE_PARSE_FAILED: 'Brave response parse failed.',
  AGENT_COERCE_FINAL: 'Agent coerced to final.',
  AGENT_COERCE_FAILED: 'Agent coercion failed.',
  REALTIME_CLIENT_CONNECTED: 'Realtime client connected.',
  REALTIME_CLIENT_DISCONNECTED: 'Realtime client disconnected.',
  REALTIME_CLIENT_INVALID: 'Realtime client event invalid.',
  REALTIME_DISABLED: 'Realtime disabled. Closing client.',
  REALTIME_PROPERTIES_DISABLED: 'Realtime properties disabled. Closing client.',
  REALTIME_MISSING_CONFIG: 'Realtime config missing. Closing client.',
  REALTIME_WS_SERVER_READY: 'Realtime WS server ready. path: ',
  REALTIME_PROPERTIES_WS_SERVER_READY:
    'Realtime properties WS server ready. path: ',
  REALTIME_CLIENT_ROUTE: 'Realtime client route: ',
  REALTIME_OPENAI_CONNECTING: 'Realtime OpenAI socket connecting. url: ',
  REALTIME_OPENAI_CONNECTED: 'Realtime OpenAI socket connected.',
  REALTIME_OPENAI_CLOSED: 'Realtime OpenAI socket closed.',
  REALTIME_OPENAI_ERROR: 'Realtime OpenAI socket error.',
  REALTIME_OPENAI_ERROR_DETAIL: 'Realtime OpenAI error detail: ',
  REALTIME_OPENAI_EVENT: 'Realtime OpenAI event: ',
  REALTIME_OPENAI_EVENT_UNPARSED: 'Realtime OpenAI event unparsed.',
  REALTIME_UPGRADE: 'Realtime upgrade request: ',
  REALTIME_UPGRADE_UNHANDLED: 'Realtime upgrade unhandled path: ',
  REALTIME_CLIENT_EVENT: 'Realtime client event: ',
  REALTIME_CLIENT_AUDIO_APPEND: 'Realtime client audio append count: ',
  REALTIME_SESSION_UPDATE: 'Realtime session update.',
  REALTIME_SESSION_TOOLS: 'Realtime session tools: ',
  REALTIME_TOOL_CALL: 'Realtime tool call.',
  REALTIME_TOOL_CALL_NAME: 'Realtime tool call name: ',
  REALTIME_TOOL_CALL_FAILED: 'Realtime tool call failed.',
  REALTIME_CLIENT_EVENT_SKIPPED: 'Realtime client event skipped: ',
  WEBRTC_SESSION_CREATED: 'WebRTC session created. id: ',
  WEBRTC_SESSION_EXPIRED: 'WebRTC session expired. id: ',
  WEBRTC_SIGNALING_CONNECTED: 'WebRTC signaling connected.',
  WEBRTC_SIGNALING_DISCONNECTED: 'WebRTC signaling disconnected.',
  WEBRTC_SIGNALING_MESSAGE: 'WebRTC signaling message: ',
  WEBRTC_PEER_CONNECTED: 'WebRTC peer connected.',
  WEBRTC_PEER_DISCONNECTED: 'WebRTC peer disconnected.',
  WEBRTC_PEER_FAILED: 'WebRTC peer connection failed.',
  WEBRTC_DATA_CHANNEL_OPEN: 'WebRTC data channel open.',
  WEBRTC_DATA_CHANNEL_CLOSED: 'WebRTC data channel closed.',
  WEBRTC_AUDIO_SINK_READY: 'WebRTC audio sink ready.',
  WEBRTC_AUDIO_SOURCE_READY: 'WebRTC audio source ready.',
  WEBRTC_WS_SERVER_READY: 'WebRTC signaling server ready. path: ',
  RAG_DATA_LOADED: 'RAG data loaded. entries: ',
  RAG_DATA_LOAD_FAILED: 'RAG data load failed.',
};
